version: '3'

services:
  ocsapplication:
    image: ocsinventory/ocsinventory-docker-image:2.12
    container_name: ocsinventory-server
    restart: always
    ports:
      - "8181:80"  # Mapea el puerto 8181 del host al puerto 80 del contenedor
    volumes:
      - "perlcomdata:/etc/ocsinventory-server"
      - "ocsreportsdata:/usr/share/ocsinventory-reports/ocsreports/extensions"
      - "varlibdata:/var/lib/ocsinventory-reports"
      - "httpdconfdata:/etc/apache2/conf-available"
    environment:
      OCS_DB_SERVER: ocsinventory-db
      OCS_DB_USER: ocsuser
      OCS_DB_PASS: ocspass
      OCS_DB_NAME: ocsweb
      # See documentation to set up SSL for MySQL
      OCS_SSL_ENABLED: 0
    links:
      - ocsdb
    networks:
      - localocs
    depends_on:
      - ocsdb    

  ocsdb:
    image: mysql:8.0
    container_name: ocsinventory-db
    restart: always
    ports:
      - "3306"  # Asegúrate de que el puerto 3306 esté disponible en el host si es necesario
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - sqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: ocsuser
      MYSQL_PASSWORD: ocspass
      MYSQL_DATABASE: ocsweb
    networks:
      - localocs
  
networks:
  localocs:

volumes:
  perlcomdata:
  ocsreportsdata:
  varlibdata:
  httpdconfdata:
  sqldata: